image: python:3.9

test:
    stage: test
    before_script:
        - pip install pytest numpy scipy
    script:
        - pytest tests

pages:
    stage: deploy
    before_script:
        - pip install pdoc
        - pip install --pre jupyterlite
    script:
        - pdoc -o public/apidoc src/hdroller
        - jupyter lite build --output-dir public/notebooks --contents notebooks
    artifacts:
        paths:
        - public
    only:
    - master
