image: python:3.9

test:
    stage: test
    before_script:
        - pip install pytest numpy scipy
    script:
        - pytest tests
    only:
        changes:
            - .gitlab-ci.yml
            - src/**/*
            - tests/**/*

pages:
    stage: deploy
    before_script:
        - pip install jupyterlab_server pdoc
        - pip install --pre jupyterlite
    script:
        - pdoc --favicon "../die.png" -o public/apidoc src/hdroller
        - jupyter lite build
    artifacts:
        paths:
        - public
    only:
    - master
