image: python:3.9

test:
    stage: test
    before_script:
        - pip install pytest numpy scipy
    script:
        - pytest tests

apidoc:
    stage: deploy
    before_script:
        - pip install pdoc
    script:
        - pdoc -o public/apidoc src/hdroller
    artifacts:
        paths:
        - public
    only:
    - master

notebooks:
    stage: deploy
    before_script:
        - pip install --pre jupyterlite
        - pip install jupyterlab_server
    script:
        - jupyter lite build --contents notebooks --output-dir public/notebooks
    artifacts:
        paths:
        - public
    only:
    - master
