image: python:3.9

pages:
    stage: deploy
    before_script:
        - pip install pdoc
    script:
        - pdoc -o public/apidoc src/hdroller
    artifacts:
        paths:
        - public
    only:
    - master
