image: python:3.9

test:
    stage: test
    before_script:
        - pip install pytest numpy scipy
    script:
        - pytest tests

pages:
    stage: deploy
    before_script:
        - pip install pdoc
    script:
        - pdoc -o public/apidoc src/hdroller
    artifacts:
        paths:
        - public
    only:
    - master
