name: Deploy Readme

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'README.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy Readme
        run: |
          mkdir -p dist/
          cp README.* dist/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
          clean: false
