name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '>=3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy scipy
      - name: Run Tests
        run: pytest tests
